baseURL = 'https://ptrtoj.com/'
title = 'a Pointer to J'
copyright = '© [WooHyoung Jeon](mailto:jeon@ptrtoj.com)'
theme = 'PaperMod'
#pagenate = 5
#languageCode = 'ko-kr'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentUseClasses = true

mainsections = ["posts"]

[minify]
disableXML = true

[params]
env = 'production'
description = "Jeon's Personal Kasten of Knowledge"
keywords= ["Blog", "Dev", "Korean", "Zettelkasten"]
author = "WooHyoung Jeon"
defaultTheme = "auto"
showShareButtons = false
showReadingTime = true
showPostNavLinks = true
showBreadCrumbs = true
showCodeCopyButtons = true
showAllPagesInArchive = true
showPageNums = true
showToc = true

[params.homeInfoParams]
Title = "Jeon's Personal Kasten of Knowledge"
Content = '''
Check [Author](https://ptrtoj.com/author) page for more information about me.

[Log](https://ptrtoj.com/log) page was moved to 'posts' dir.

Each posts' URLs are frequently changed because of the author's inconsistency. Please rather remember the main domain 'ptrtoj.com' for later reference.
'''

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/ptrtoj'
[[params.socialIcons]]
name = 'X'
url = 'https://twitter.com/ptrtoj'
[[params.socialIcons]]
name = 'Instagram'
url = 'https://www.instagram.com/ptrtoj/'
[[params.socialIcons]]
name = 'email'
url = 'jeon@ptrtoj.com'
[[params.socialIcons]]
name = 'youtube'
url = 'https://youtube.com/@뉴스채널'

[markup]
[markup.highlight]
style = 'catppuccin-latte'
[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = 'Home'
url = '/'
weight = 1
[[menu.main]]
name = 'Author'
url = '/author'
weight = 3
[[menu.main]]
name = 'Search'
url = '/s'
weight = 4

[outputs]
home = ["HTML", "RSS", "JSON"]