baseURL = 'https://ptrtoj.com/'
title = 'a Pointer to J'
copyright = 'Â© [WooHyung Jeon](mailto:jeon@ptrtoj.com)'
theme = 'PaperMod'
pagenate = 5
#languageCode = 'ko-kr'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentUseClasses = true

mainsections = ["posts"]

[minify]
disableXML = true

[params]
env = 'production'
description = 'a Super Minimal Blog'
author = "WooHyung Jeon"
defaultTheme = "auto"
showShareButtons = true
showReadingTime = true
showPostNavLinks = true
showBreadCrumbs = true
showCodeCopyButtons = true
showAllPagesInArchive = true
showPageNums = true
showToc = true

[params.homeInfoParams]
Title = "Jeon's Minimal Blog"
Content = '''
Check [Author](https://ptrtoj.com/author) page for more information about ME ğŸ”¥

(ë„ë©”ì¸ `withjeon.com`ì€ 24ë…„ ì—°ë§ ì—°ì¥ ë¯¸ê°±ì‹  ì˜ˆì •ì…ë‹ˆë‹¤. `ptrtoj.com`ì„ ì‚¬ìš©í•´ì£¼ì„¸ìš”!)
'''

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/ptrtoj'
[[params.socialIcons]]
name = 'X'
url = 'https://twitter.com/ptrtoj'
[[params.socialIcons]]
name = 'Instagram'
url = 'https://www.instagram.com/ptrtoj/'
[[params.socialIcons]]
name = 'email'
url = 'jeon@ptrtoj.com'
[[params.socialIcons]]
name = 'youtube'
url = 'https://youtube.com/@cruxnewsteam'

[markup]
[markup.highlight]
style = 'catppuccin-latte'
[[menu.main]]
name = 'Home'
url = '/'
weight = 1
[[menu.main]]
name = 'All Posts'
url = '/posts'
weight = 2
[[menu.main]]
name = 'Links'
url = '/links'
weight = 3
[[menu.main]]
name = 'Author'
url = '/author'
weight = 4
[[menu.main]]
name = 'Updates'
url = '/log'
weight = 5
